story5_app/urls.py
from django.urls import path

from . import views

app_name = 'story5_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah_matkul/', views.tambah_matkul, name='tambah_matkul'),
    path('matkul/<int:id>', views.detail_matkul, name='detail_matkul'),
    path('delete_matkul/<int:id>', views.hapus_matkul, name='hapus_matkul')
]

story5_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5_app.urls')),
    path('story6_app/', include('story6_app.urls'))
]

story5_app/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
pilihan_semester = [
    ("Gasal 2019/2020", "Gasal 2019/2020"),
    ("Genap 2019/2020", "Genap 2019/2020"),
    ("Gasal 2020/2021", "Gasal 2020/2021"),
    ("Genap 2020/2021", "Genap 2020/2021"),
    ("Gasal 2021/2022", "Gasal 2021/2022"),
    ("Genap 2021/2022", "Genap 2021/2022"),
    ("Gasal 2022/2023", "Gasal 2022/2023"),
    ("Genap 2022/2023", "Genap 2022/2023")
]
class MataKuliah(models.Model):
    nama = models.TextField(max_length = 40)
    dosen = models.TextField(max_length = 40)
    jumlah_sks = models.IntegerField()
    deskripsi = models.TextField(max_length = 400)
    semester = models.TextField(choices = pilihan_semester)
    ruangan = models.TextField(max_length = 40)

    def __str__(self):
        return "{} ({})".format(self.nama, self.dosen)

    def get_absolute_url(self):
        return reverse("story5_app:detail_matkul", args=[self.id])

story5_app/forms.py
from django.forms import ModelForm
from .models import MataKuliah

class MataKuliahForm(ModelForm):
    class Meta:
        model = MataKuliah
        fields = "__all__"

story5_app/views.py
from django.shortcuts import render, redirect
from .models import MataKuliah
from .forms import MataKuliahForm
from django.contrib import messages

def index(request):
    context = {
        'mata_kuliah_list' : MataKuliah.objects.all().order_by("id"),
        'page' : 'index'
    }
    return render(request, 'story5_app/index.html', context)

def tambah_matkul(request):
    if request.method == 'POST':
        matkul_form = MataKuliahForm(request.POST)
        if matkul_form.is_valid():
            matkul_form.save()
            messages.add_message(request, messages.SUCCESS, 'Mata Kuliah {} berhasil ditambahkan'.format(request.POST['nama']))
        return redirect('story5_app:index')
    context = {
        'page' : 'tambah_matkul'
    }
    return render(request, 'story5_app/tambah_matkul.html', context)

def detail_matkul(request, id):
    context = {
        'mata_kuliah' : MataKuliah.objects.get(id=id)
    }
    return render(request, 'story5_app/detail_matkul.html', context)

def hapus_matkul(request, id):
    if request.method == 'POST':
        mata_kuliah = MataKuliah.objects.get(id=id)
        mata_kuliah.delete()
        messages.add_message(request, messages.SUCCESS, 'Mata Kuliah {} berhasil dihilangkan'.format(mata_kuliah.nama))
    return redirect('story5_app:index')

story5_app/templates/story5_app/detail_matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail Mata Kuliah</title>
{% endblock meta %}

{% block content %}
<div class="main pt-3">
    <div class="container">
        <div class="rounded-lg mb-3 p-3 card-form">
            <h3>Mata Kuliah {{ mata_kuliah.nama }}</h3>
            <div class="col p-auto m-auto">
                <p>Semester {{ mata_kuliah.semester }}</p>
            </div>
            <div class="col p-auto m-auto">
                <p>Ruangan perkuliahan di {{ mata_kuliah.ruangan }}</p>
            </div>
            <div class="col p-auto m-auto">
                <p>Dosen pengajar adalah {{ mata_kuliah.dosen }}</p>
            </div>
            <div class="col p-auto m-auto">
                <p>Kuliah ini mengambil {{ mata_kuliah.jumlah_sks }} SKS</p>
            </div>
            <div class="detail-description rounded-lg p-2">
                {{ mata_kuliah.deskripsi }}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

story5_app/templates/story5_app/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 5 Hadi</title>
{% endblock meta %}

{% block content %}
    {% for mata_kuliah in mata_kuliah_list %}
    <div class="card-form p-3 row mb-3 rounded-lg">
      <div class="col-9">
        <h2 class="p-auto m-auto">
          <a class="link-matkul" href="{{mata_kuliah.get_absolute_url}}">
            {{mata_kuliah.nama}}
          </a>
        </h2>
        <p class="p-auto m-auto">Ruangan perkuliahan di {{mata_kuliah.ruangan}}</p>
        <p class="p-auto m-auto">Klik nama mata kuliah untuk melihat lebih lanjut</p>
      </div>
      <div class="col-3 d-flex justify-content-center align-items-center">
        <form action="{% url 'story5_app:hapus_matkul' mata_kuliah.id %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger" type="input>">
            Hapus mata kuliah
          </button>
        </form>
      </div>
    </div>
    {% empty %}
    <h2 class="text-center">Silakan masukkan mata kuliah di bagian "Tambah Mata Kuliah"</a></h2>
    {% endfor %}
  </div>
</div>
{% endblock content %}

story5_app/templates/story5_app/tambah_matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Mata Kuliah</title>
{% endblock meta %}

{% block content %}
    <div class="main pt-3">
        <h2 class="text-center">Tambah Mata Kuliah</h2>
        <div class="container">
            <div class="rounded-lg mb-3 p-3 card-form">
                <form method="POST" action="{% url 'story5_app:tambah_matkul' %}">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="nama-matkul" class="col-sm-2 col-form-label">Matkul</label>
                        <div class="col-sm-10">
                            <input class="form-control" id="nama-matkul" placeholder="Nama mata kuliah" name="nama" required>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col">
                            <p class="p-auto m-auto">Pilihan Semester</p>
                            <select class="form-control mb-1" name="semester" required>
                                <option value="Gasal 2019/2020">Gasal 2019/2020</option>
                                <option value="Genap 2019/2020">Genap 2019/2020</option>
                                <option value="Gasal 2020/2021">Gasal 2020/2021</option>
                                <option value="Genap 2020/2021">Genap 2020/2021</option>
                                <option value="Gasal 2021/2022">Gasal 2021/2022</option>
                                <option value="Genap 2021/2022">Genap 2021/2022</option>
                                <option value="Gasal 2022/2023">Gasal 2022/2023</option>
                                <option value="Genap 2022/2023">Genap 2022/2023</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="ruangan-matkul" class="col-sm-2 col-form-label">Ruangan</label>
                        <div class="col-sm-10">
                            <input class="form-control" id="ruangan-matkul" placeholder="Nama/kode ruangan" name="ruangan" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="dosen-matkul" class="col-sm-2 col-form-label">Dosen</label>
                        <div class="col-sm-10">
                            <input class="form-control" id="dosen-matkul" placeholder="Dosen pengajar" name="dosen" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="sks-matkul" class="col-sm-2 col-form-label">SKS</label>
                        <div class="col-sm-10">
                            <input type="number" min="1" max="10" placeholder="Masukkan angka 1-10" class="form-control" id="sks-matkul" name="jumlah_sks" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <textarea placeholder="Deskripsi singkat mata kuliah (max 400 karakter)" class="form-control input-description p-2 m-4" name="deskripsi" required></textarea>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-10">
                          <button type="submit" class="btn btn-primary">Tambah Mata Kuliah</button>
                        </div>
                    </div>     
                </form>
            </div>
        </div>
    </div>
{% endblock content %}