story5_app/urls.py
from django.urls import path

from . import views

app_name = 'story5_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah_matkul/', views.tambah_matkul, name='tambah_matkul'),
    path('matkul/<int:id>', views.detail_matkul, name='detail_matkul'),
    path('delete_matkul/<int:id>', views.hapus_matkul, name='hapus_matkul')
]

story5_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5_app.urls')),
    path('story6_app/', include('story6_app.urls'))
]

story6_app/urls.py
from django.urls import path
from . import views

app_name = "story6_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("tambah_peserta/<int:id>", views.tambah_peserta, name="tambah_peserta"),
    path("tambah_kegiatan/", views.tambah_kegiatan, name="tambah_kegiatan"),
    path("hapus_peserta/", views.hapus_peserta, name="hapus_peserta"),
    path("detail_peserta/<str:nama>", views.detail_peserta, name="detail_peserta"),
    path("detail_kegiatan/<str:nama>", views.detail_kegiatan, name="detail_kegiatan")
]

story6_app/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

class Peserta(models.Model):
    nama = models.TextField(max_length=50, unique=True)

    def __str__(self):
        return self.nama
    
    def get_absolute_url(self):
        nama_link = self.nama.replace(" ", "-")
        return reverse("story6_app:detail_peserta", args=[nama_link])
    
class Kegiatan(models.Model):
    nama = models.TextField(max_length=70, unique=True)
    peserta = models.ManyToManyField(Peserta, blank=True)

    def __str__(self):
        return self.nama
    
    def get_absolute_url(self):
        nama_link = self.nama.replace(" ", "-")
        return reverse("story6_app:detail_kegiatan", args=[nama_link])
    

story6_app/forms.py
from django import forms
from .models import Kegiatan, Peserta

class PesertaForm(forms.ModelForm):
    nama = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class" : "form-control",
                "placeholder" : "Nama Peserta"
                }),
        label="")
    class Meta:
        model = Peserta
        fields = "__all__"

class KegiatanForm(forms.ModelForm):
    nama = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class" : "form-control w-50 text-center",
                "placeholder" : "Nama Kegiatan"
            }),
        label=""
    )
    class Meta:
        model = Kegiatan
        # Di form cuma ingin input nama kegiatan saja
        # add peserta bisa memakai PesertaForm
        exclude = ["peserta"]

story6_app/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Peserta, Kegiatan
from .forms import PesertaForm, KegiatanForm
from django.contrib import messages
# Create your views here.

def index(request):
    context = {
        "kegiatan_items" : Kegiatan.objects.all(),
        "peserta_form" : PesertaForm,
        "is_index" : True, # Untuk memberi CSS style
        "is_story6_app" : True
    }
    return render(request, "story6_app/index.html", context)

def tambah_peserta(request, id):
    if request.method == "POST":
        kegiatan = Kegiatan.objects.get(id=id)
        nama_peserta_baru = request.POST["nama"]
        # Supaya bisa memilih penambahan peserta yang sesuai kriteria
        # peserta_baru tipenya Peserta, status_baru tipenya boolean
        peserta_baru, status_baru = Peserta.objects.get_or_create(nama=nama_peserta_baru)
        if status_baru:
            # Tambah peserta baru yang belum ada sama sekali
            peserta_baru.save()
            # Masukkan peserta ke kegiatan yang sesuai
            kegiatan.peserta.add(peserta_baru)
            messages.add_message(request, messages.SUCCESS, "Peserta {} ditambahkan ke {}".format(nama_peserta_baru, kegiatan.nama))
        else: # Ada 2 kemungkinan, sudah ada di kegiatan itu
        #atau belum ada tapi sudah ada di database.
            try:
                # Coba cari adakah peserta di kegiatan ini
                kegiatan.peserta.get(nama=nama_peserta_baru) # Line ini akan error jika tidak ada pesertanya
                # jika tidak error, tandanya sudah ada peserta dengan nama nama_peserta_baru, jangan tambahkan.
                messages.add_message(request, messages.WARNING, "Peserta {} sudah ada di kegiatan {}".format(nama_peserta_baru, kegiatan.nama))
            except:
                # Kalau tadi error, maka nama sudah ada di kegiatan lain, tapi disini belum
                # Boleh ditambahkan
                kegiatan.peserta.add(peserta_baru)
                messages.add_message(request, messages.SUCCESS, "Peserta {} ditambahkan ke {}".format(nama_peserta_baru, kegiatan.nama))
    # redirect("/detail_kegiatan/nama-kegiatan")
    return redirect(reverse("story6_app:detail_kegiatan", args=[kegiatan.nama.replace(" ", "-")]))

def tambah_kegiatan(request):
    if request.method == "POST":
        kegiatan_form = KegiatanForm(request.POST)
        if kegiatan_form.is_valid():
            # kegiatan_object cuma buat ambil nama kegiatan
            kegiatan_object = kegiatan_form.save(commit=False)
            # Dibetulin format namanya
            nama_kegiatan = kegiatan_object.nama.replace(" ", "-")
            kegiatan_form.save() #Baru disave akhrinya
        return redirect(reverse("story6_app:detail_kegiatan", args=[nama_kegiatan]))
    # Kalo request.method == "GET"
    context = {
        "kegiatan_form" : KegiatanForm,
        "is_tambah_kegiatan" : True,
        "is_story6_app" : True
    }
    return render(request, "story6_app/tambah_kegiatan.html", context)

def hapus_peserta(request):
    if request.method == "POST":
        try:
            # Coba kita ambil object pesertanya
            peserta = Peserta.objects.get(nama=request.POST["nama"])
            kegiatan = Kegiatan.objects.get(id=request.POST["kegiatan_id"])
        except:
            # Kalo masuk sini, tandanya gaketemu. Langsung redirect ke index aja.
            messages.add_message(request, messages.WARNING, "Peserta {} tidak terdaftar di kegiatan {}".format(request.POST["nama"], request.POST["kegiatan_id"]))
            return redirect("story6_app:index")
        # Kalau gamasuk except, pasti ada peserta di dalam suatu kegiatan
        kegiatan.peserta.remove(peserta) # Hapus peserta yang ikut kegiatan tersebut
        messages.add_message(request, messages.SUCCESS, "Peserta {} sudah dihapus dari {}".format(peserta.nama, kegiatan.nama))
    # redirect("/")
    return redirect("story6_app:index")

def detail_peserta(request, nama):
    nama = nama.replace("-", " ")
    peserta = get_object_or_404(Peserta, nama=nama)
    context = {
        "peserta" : peserta,
        "is_story6_app" : True
    }
    return render(request, "story6_app/detail_peserta.html", context)

def detail_kegiatan(request, nama):
    nama = nama.replace("-", " ")
    kegiatan = get_object_or_404(Kegiatan, nama=nama)
    context = {
        "kegiatan" : kegiatan,
        "peserta_form" : PesertaForm,
        "is_story6_app" : True
    }
    return render(request, "story6_app/detail_kegiatan.html", context)

story6_app/templates/story6_app/detail_kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail Kegiatan</title>
{% endblock meta %}

{% block content %}
<div class="row">
    <div class="col-lg-8 col-sm-12">
        <h1><a class="kegiatan-content" href="{{kegiatan.get_absolute_url}}">Nama Kegiatan: {{kegiatan.nama}}</a></h1>
        <ol class="px-5">
            <form action="{% url 'story6_app:hapus_peserta' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" value={{kegiatan.id}} name="kegiatan_id">
                {% for peserta in kegiatan.peserta.all %}
                    <li>
                        <a class="kegiatan-content" href="{{peserta.get_absolute_url}}">{{peserta.nama}}</a>
                        <button class="ml-1 px-1 text-light border-0 p-0 bg-danger d-inline" value="{{peserta.nama}}" name="nama" type="submit">Hapus Peserta</button>
                    </li>
                    <br>
                {% endfor %}
            </form>
        </ol>
    </div>

    <div class="col-lg-4 col-sm-12">
        <div class="card-form p-3 rounded-lg text-center">
            <h3>Tambah Peserta</h3>
            <form action="{% url 'story6_app:tambah_peserta' id=kegiatan.id %}" method="POST" class="d-flex justify-content-center align-items-center flex-column mt-2">
                {% csrf_token %}
                {{peserta_form}}
                <input class="btn btn-primary mt-2" type="submit" value="Tambah Peserta">
            </form>
        </div>
    </div>
</div>
<!--Janlup tambahin 2 </div> biar ketutup (DONE)-->
</div>
</div>
{% endblock content %}

story6_app/templates/story6_app/detail_peserta.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Detail Peserta</title>
{% endblock meta %}

{% block content %}
<h1>Keterangan peserta {{peserta.nama}}</h1>
<h3>Kegiatan yang diikuti ada {{peserta.kegiatan_set.all|length}}, yaitu</h3>
<ol>
    {% for kegiatan in peserta.kegiatan_set.all %}
    <li><a class="kegiatan-content" href="{{kegiatan.get_absolute_url}}">{{kegiatan.nama}}</a></li>
    {% endfor %}
</ol>
<!--Janlup tambahin 2 </div> biar ketutup (DONE)-->
</div>
</div>
{% endblock content %}

story6_app/templates/story6_app/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6 Hadi</title>
{% endblock meta %}

{% block content %}
<div class="row px-2">
    {% for kegiatan in kegiatan_items %}
    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="card-form p-2 rounded-lg d-flex justify-content-center align-items-center flex-column mb-3 border border-white">
            <h3>
                <a class="kegiatan-content" href="{{kegiatan.get_absolute_url}}">{{kegiatan.nama}}</a>
            </h3>
            <h4>Peserta:</h4>
            <div class="overflow-auto list-peserta">
                <ol class="px-5">
                    <form action="{% url 'story6_app:hapus_peserta' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" value="{{kegiatan.id}}" name="kegiatan_id">
                        {% for peserta in kegiatan.peserta.all %}
                            <li>
                                <a class="kegiatan-content" href="{{peserta.get_absolute_url}}">{{peserta.nama}}</a>
                                <button class="ml-1 px-1 text-light border-0 p-0 bg-danger d-inline" value="{{peserta.nama}}" name="nama" type="submit">Hapus Peserta</button>
                            </li>
                        {% endfor %}
                    </form>
                </ol>
            </div>
            <div>
                <form action="{% url 'story6_app:tambah_peserta' id=kegiatan.id %}" method="POST" class="d-flex justify-content-center align-items-center flex-column mt-2">
                    {% csrf_token %}
                    {{peserta_form}}
                    <input class="btn btn-primary mt-2" type="submit" value="Tambah Peserta">
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    <h1 class="text-center">Silakan tambahkan kegiatan baru di bagian "Tambah Kegiatan Baru"</h1>
    {% endfor %}
</div>
<!--Janlup tambahin 2 </div> biar ketutup (DONE)-->
</div>
</div>
{% endblock content %}

story6_app/templates/story6_app/tambah_kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Tambah Kegiatan</title>
{% endblock meta %}

{% block content %}
<div>
    <form class="d-flex justify-content-center align-items-center flex-column" action="{% url 'story6_app:tambah_kegiatan' %}" method="POST">
        <h3>Tambah Kegiatan</h3>
        {% csrf_token %}
        {{kegiatan_form}}
        <input class="btn btn-primary mt-2" type="submit" value="Tambahkan Kegiatan">
    </form>
</div>
<!--Janlup tambahin 2 </div> biar ketutup (DONE)-->
</div>
</div>
{% endblock content %}