story5_app/urls.py
from django.urls import path

from . import views

app_name = 'story5_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('tambah_matkul/', views.tambah_matkul, name='tambah_matkul'),
    path('matkul/<int:id>', views.detail_matkul, name='detail_matkul'),
    path('delete_matkul/<int:id>', views.hapus_matkul, name='hapus_matkul')
]

story5_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5_app.urls')),
    path('story6_app/', include('story6_app.urls'))
]

story6_app/urls.py
from django.urls import path
from . import views

app_name = "story6_app"

urlpatterns = [
    path("", views.index, name="index"),
    path("tambah_peserta/<int:id>", views.tambah_peserta, name="tambah_peserta"),
    path("tambah_kegiatan/", views.tambah_kegiatan, name="tambah_kegiatan"),
    path("hapus_peserta/", views.hapus_peserta, name="hapus_peserta"),
    path("detail_peserta/<str:nama>", views.detail_peserta, name="detail_peserta"),
    path("detail_kegiatan/<str:nama>", views.detail_kegiatan, name="detail_kegiatan")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% if is_story6_app != True %}
  <nav class="navbar navbar-expand-lg navbar-light bg-navbar">
    <a class="navbar-brand" href="#">Hadi's Matkul List</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        {% if page == 'index' %}
        <a class="nav-item nav-link active" href="{% url 'story5_app:index' %}"> Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'story5_app:tambah_matkul' %}"> Tambah Mata Kuliah </a>
        {% elif page == 'tambah_matkul' %}
        <a class="nav-item nav-link" href="{% url 'story5_app:index' %}"> Home </a>
        <a class="nav-item nav-link active" href="{% url 'story5_app:tambah_matkul' %}"> Tambah Mata Kuliah <span class="sr-only">(current)</span></a>
        {% else %}
        <a class="nav-item nav-link" href="{% url 'story5_app:index' %}"> Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'story5_app:tambah_matkul' %}"> Tambah Mata Kuliah </a>
        {% endif %}
      </div>
    </div>
  </nav>
  {% else %}
  <nav class="navbar navbar-expand-lg navbar-light bg-navbar">
    <a class="navbar-brand" href="#">Pengaturan Kegiatan</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link
          {% if is_index %}
            active
          {% endif %}
          " href="{% url 'story6_app:index' %}">List Kegiatan</a>
        <a class="nav-item nav-link
          {% if is_tambah_kegiatan %}
            active
          {% endif %}
        " href="{% url 'story6_app:tambah_kegiatan' %}">Tambah Kegiatan Baru</a>
      </div>
    </div>
  </nav>
  {% endif %}
  <div class="main pt-3">
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}} alert-dismissible show fade" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}
  {% block content %}
  {% endblock content %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>